[flavor]
dark = "vscode-dark-plus"

#[status]
#sep_left = { open = "", close = "" }
#sep_right = { open = "", close = "" }

# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/theme-dark.toml
# Overrides were added to make it work on SAW that doesn't have the right font
[icon]
dirs  = [
    { name = "*", text = " " },
]
files = [
    { name = "*", text = " " },
]
exts  = [
    { name = "*", text = " " },
]
#conds = []

# Win+; to find emojis
prepend_conds = [
  { if = "hidden & dir",  text = "👻" },  # Hidden directories
  { if = "dir",           text = "📂" },  # Directories
  { if = "!(dir | link)", text = "📄" },  # Normal files (not directories or symlinks)
]
